name: dotnetcore3

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - uses: actions/upload-artifact@v1
      with:
        name: mybaseconsole
        path: /home/runner/work/my-base-console-app/my-base-console-app/MyBaseConsoleApp/bin/Release/netcoreapp3.0/